/*
Winston Phillips
T00212039
9/12/2017
Advanced Math Tutor
*/
#include <iomanip>
#include <iostream>
#include <cstdlib>
#include <fstream>
#include "randomInt.h"


using namespace std;

int main()
{

/**************Variables**************/
	int num1, num2;		// random numbers generated by computer
	int Answer;			// actual answer
	int inputAns;		// inputed answer from the user
	int compSum;		// sum of two computer numbers
	float localGames = 0;	// times played
	float localCorrect = 0; 	// time correct
	float localAverage = 0.0f;  		// average just for this game
	char userChar;				// char to be inputed by user during loop
/**************Main Output************/

	seedRand();				// initializes srand()
do
 {
	randomInt1(num1);		// generates first random integer

	randomInt2(num2);		// generates second random integer

	compSum = num1 + num2;

	cout << setw(10) << num1 << endl;
	cout << setw(5) << "+" <<  setw(5) << num2 << endl;
	cout << setw(10) << "---" << endl;
	cout << setw(7) << " ";		// so inputed answer lines up
		
		bool valid = false;		// making user input an integer
		do
		{
			cin >> inputAns;

			if (cin.good())		// if input is an integer
			{
				valid = true;
			}

			else 				// if input is not an integer
			{
				cin.clear();
				cin.ignore();
				cout << "Invalid input. Please try again: ";
			}

		} while(!valid);

		

	if (inputAns == compSum)
	{
		cout << "That is correct!" << endl;
		localCorrect++;
	}
	else
	{
		cout << "I am sorry, that is incorrect. The correct answer is " << compSum << endl;
	}
	localGames++;

	 cout << endl;
	 cout << "Would you like to play again? (y/n) : ";		// prompts user if he/she want to play again
	 	cin >> userChar;

	 while (userChar != 'y' && userChar != 'n')				// input validation for userChar
	 {
	 	cout << "Incorrect Option entered. Please enter a y or an n : ";
	 		cin >> userChar;
	 }

 }while (userChar == 'y');

 localAverage = (((static_cast<float>(localCorrect) / localGames)) * 100);		// calculates average correct of local game

 cout << endl;
 cout << "This session you had " << localCorrect << " correct answer on " << localGames << " questions, meaning you scored "; 
 cout  << setprecision(3) << localAverage << "%";
 cout << "\n\n";

 /********************File I/O Operations*****************************************/

float overalGames;
float overalCorrect;		
float overalAverage;

 ofstream writeTo;		// reading to a File
 ifstream writeFrom;    // reading from a file

 writeFrom.open("math.txt");
 	writeFrom >> overalGames;
 	writeFrom >> overalCorrect;	 // overall games on first line, overall correct on second 
 	cout << overalCorrect;
 	writeFrom.close();


 	overalGames = overalGames + localGames;		// adds the number of games played locally to overall games

 	overalCorrect = overalCorrect + localCorrect;	// adds the number of local correct answers to overall correct answers

 	overalAverage = static_cast<float>((overalCorrect/overalGames) * 100);		// calculates overall average

 	

 	cout << "Overall you have answered " << overalCorrect << " questions correctly out of " << overalGames << " asked for a score of ";
 	cout << setprecision(3) <<  overalAverage << "%" << endl;

 writeTo.open("math.txt");
 	writeTo << overalGames << endl;		// writes new data to file for next use
 	writeTo << overalCorrect;

 	
 	writeTo.close();




	return 0;
}